interface TicketTemplateProps {
    operator: string;
    type: string;
    status: string;
    from: string;
    to: string;
    date: string;
    time: string;
    passengerName: string;
    seat: string;
    travelClass: string;
    confirmationRef: string;
}

export const generateTicketHTML = ({
    operator,
    type,
    status,
    from,
    to,
    date,
    time,
    passengerName,
    seat,
    travelClass,
    confirmationRef
}: TicketTemplateProps) => {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }
    body { background: #F8FAFC; padding: 40px; color: #0F172A; }
    .card { background: white; border-radius: 24px; overflow: hidden; box-shadow: 0 8px 30px rgba(0,0,0,0.08); max-width: 600px; margin: 0 auto; }
    .header { background: #003580; padding: 32px; display: flex; justify-content: space-between; align-items: center; }
    .header h1 { color: white; font-size: 22px; font-weight: 700; }
    .header .badge { background: #10B981; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 700; }
    .route-row { display: flex; justify-content: space-between; align-items: center; padding: 32px; border-bottom: 1px solid #F1F5F9; }
    .city { font-size: 36px; font-weight: 800; color: #0F172A; }
    .city-label { font-size: 11px; color: #94A3B8; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
    .arrow { font-size: 28px; color: #CBD5E1; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0; }
    .grid-item { padding: 20px 32px; border-bottom: 1px solid #F1F5F9; }
    .grid-item:nth-child(odd) { border-right: 1px solid #F1F5F9; }
    .label { font-size: 10px; color: #94A3B8; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }
    .value { font-size: 15px; font-weight: 700; color: #0F172A; }
    .qr-section { text-align: center; padding: 32px; border-top: 2px dashed #E2E8F0; }
    .qr-section img { width: 130px; height: 130px; }
    .ref { margin-top: 12px; font-size: 12px; color: #94A3B8; letter-spacing: 2px; font-weight: 700; }
    .footer { background: #F8FAFC; text-align: center; padding: 16px; font-size: 11px; color: #CBD5E1; }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <div>
        <p style="color:rgba(255,255,255,0.6);font-size:11px;text-transform:uppercase;letter-spacing:1px">Carrier</p>
        <h1>${operator || 'Easy Route'}</h1>
        <p style="color:rgba(255,255,255,0.5);font-size:12px;margin-top:4px">${type.toUpperCase()} TICKET</p>
      </div>
      <span class="badge">${status.toUpperCase()}</span>
    </div>

    <div class="route-row">
      <div>
        <div class="city">${from}</div>
        <div class="city-label">Origin</div>
      </div>
      <div class="arrow">✈</div>
      <div style="text-align:right">
        <div class="city">${to}</div>
        <div class="city-label">Destination</div>
      </div>
    </div>

    <div class="grid">
      <div class="grid-item"><div class="label">Date</div><div class="value">${date}</div></div>
      <div class="grid-item"><div class="label">Departure</div><div class="value">${time}</div></div>
      <div class="grid-item"><div class="label">Passenger</div><div class="value">${passengerName}</div></div>
      <div class="grid-item"><div class="label">Seat / Class</div><div class="value">${seat} • ${travelClass}</div></div>
    </div>

    <div class="qr-section">
      <img src="https://api.qrserver.com/v1/create-qr-code/?size=130x130&data=${confirmationRef}" />
      <div class="ref">TICKET ID: ${confirmationRef}</div>
    </div>

    <div class="footer">
      Generated by Easy Route • Valid for travel on stated date only
    </div>
  </div>
</body>
</html>`;
};
